//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: BaseControllerVC, ___VARIABLE_productName:identifier___ViewProtocol {

    //MARK:- OUTLETS

    
    //MARK:- VARIABLES

    private var presenter: ___VARIABLE_productName:identifier___Presenter()

    //MARK:- LIFE CYCLE
    
	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension ___VARIABLE_productName:identifier___ViewController: PresenterToView___VARIABLE_productName:identifier___Protocol {
    
}
